services:
  login-service:
    container_name: login-service
    build:
      context: ./
      dockerfile: ./dockerfile
    networks:
      - app-network
    expose:
      - "8081"
    env_file:
      - "./.env"

networks:
  app-network:
    driver: bridge